# Generated by Django 5.0.dev20230907184726 on 2023-10-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_made',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
