# Generated by Django 4.2.4 on 2023-10-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_locations_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='rating',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
