# Generated by Django 4.2.4 on 2023-10-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_locations_description_locations_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='locations',
            name='rating',
            field=models.CharField(max_length=200),
        ),
    ]
