# Generated by Django 4.2.4 on 2023-10-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_locations_description_alter_locations_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='locations',
            name='rating',
            field=models.CharField(default='', max_length=200),
        ),
    ]
