# Generated by Django 4.2.5 on 2023-11-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_locations_description_alter_locations_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='description',
            field=models.TextField(default='None Provided'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locations',
            name='rating',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
