# Generated by Django 4.2.4 on 2023-11-05 16:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_locations_description_alter_locations_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='description',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='rating',
        ),
        migrations.AddField(
            model_name='locations',
            name='rating_average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='locations',
            name='rating_count',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('description', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='users.locations')),
            ],
        ),
    ]
