# Generated by Django 4.2.4 on 2023-12-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_locations_description_remove_locations_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='submit_user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
