# Generated by Django 4.2.4 on 2023-12-02 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_locations_submit_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='submit_user',
        ),
    ]
