# Generated by Django 4.2.4 on 2023-12-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_locations_submit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='userinfo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
