# Generated by Django 4.2.4 on 2023-12-03 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0016_locations_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='userinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
    ]
