# Generated by Django 4.2.4 on 2023-12-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_locations_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='userinfo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
