# Generated by Django 4.2.4 on 2023-12-03 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0018_alter_locations_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='userinfo',
        ),
        migrations.AddField(
            model_name='locations',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
    ]
