# Generated by Django 4.2.4 on 2023-12-03 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_feedback_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.locations'),
        ),
    ]
